#!/bin/sh


main() {
	MENU=$(gum choose "New" "Commit" "Push" "Exit");

	if [ "$MENU" = "New" ]; then
		{
			git init
			gum confirm "Add a remote ?" && REMOTE="YES" || REMOTE="NO"
			if [ $REMOTE = "YES" ]; then
				{
					ORIGIN=$(gum input --value "origin" --placeholder "Name of the remote repo");
					REMOTE=$(gum input --value "" --placeholder "Link to remote repo");
					git remote add $ORIGIN $REMOTE
				}
			fi
			main
		}
	elif [ "$MENU" = "Commit" ]; then
		{
			git add *
			TYPE=$(gum choose "🩹 Fix" "⚡ Feat" "📘 Docs" "💄 Style" "🪄 Refactor" "🔧 Test" "❌ Revert" "🧼 Clean")
			SUMMARY=$(gum input --value "$TYPE: " --placeholder "Commit Message")
			gum confirm "Commit changes ?" && git commit -m "$SUMMARY"
			main
		}
	elif [ "$MENU" = "Push" ]; then
		{
			BRANCH=$(gum input --value "origin master" --placeholder "Remote name and Branch")
			gum confirm "Push changes to $BRANCH ?" && gum spin -s points --title "Pushing to $BRANCH" -- git push -u $BRANCH
			main
		}
	else
		{
			exit
		}
	fi
}

main
